stages:
  - test

test_py37:
  image: python:3.7
  stage: test
  script:
    - python -m pip install .
    - python -m pip install pytest
    - python -m pip install toml
    - python -m pytest -v -s

test_py38:
  image: python:3.8
  stage: test
  script:
    - python -m pip install .
    - python -m pip install pytest
    - python -m pip install toml
    - python -m pytest -v -s

test_py39:
  image: python:3.9
  stage: test
  script:
    - python -m pip install .
    - python -m pip install pytest
    - python -m pip install toml
    - python -m pytest -v -s

test_py310:
  image: python:3.10
  stage: test
  script:
    - python -m pip install .
    - python -m pip install pytest
    - python -m pip install toml
    - python -m pytest -v
